export const Images = {
  logo: require('../../assets/images/logo.png'),
  home: require('../../assets/images/home.png'),
  noHome: require('../../assets/images/no-home.png'),
  browseCoaches: require('../../assets/images/browse-coaches.png'),
  noBrowseCoaches: require('../../assets/images/no-browse-coaches.png'),
  profile: require('../../assets/images/profile.png'),
  noProfile: require('../../assets/images/no-profile.png'),
  light: require('../../assets/images/light.png'),
  dark: require('../../assets/images/dark.png'),
  settings: require('../../assets/images/settings.png'),
  profilePic: require('../../assets/images/profile-pic.png'),
  xMark: require('../../assets/images/x-mark.png'),
  checkMark: require('../../assets/images/check-mark.png'),
  rotate: require('../../assets/images/rotate.png'),
  flashOn: require('../../assets/images/flash-on.png'),
  flashOff: require('../../assets/images/flash-off.png'),
  cameraSnap: require('../../assets/images/camera-snap.png'),
  arrow: require('../../assets/images/arrow.png'),
  darkProfileBackground: require('../../assets/images/dark-profile-background.jpg'),
  lightProfileBackground: require('../../assets/images/light-profile-background.jpg'),
  personalDetails: require('../../assets/images/personal-details.png'),
  personalDetailsTwo: require('../../assets/images/personal-details2.png'),
  settingsProfile: require('../../assets/images/settings-profile.png'),
  settingsProfileTwo: require('../../assets/images/settings-profile2.png'),
  phone: require('../../assets/images/phone.png'),
  privacy: require('../../assets/images/privacy.png'),
  logout: require('../../assets/images/logout.png'),
  noAffiliates: require('../../assets/images/no-affiliates.png'),
  contact: require('../../assets/images/contact.png'),
  contactTwo: require('../../assets/images/contact2.png'),
  instagram: require('../../assets/images/instagram.png'),
  facebook: require('../../assets/images/facebook.png'),
  linkedIn: require('../../assets/images/linked-in.png'),
  paperAirplane: require('../../assets/images/paper-airplane.png'),
  trash: require('../../assets/images/trash.png'),
  notification: require('../../assets/images/notification.png'),
  noNotification: require('../../assets/images/no-notification.png'),
  arrowDown: require('../../assets/images/arrow-down.png'),
  save: require('../../assets/images/save.png'),
  lock: require('../../assets/images/lock.png'),
  english: require('../../assets/images/english.png'),
  arabic: require('../../assets/images/arabic.png'),
  hebrew: require('../../assets/images/hebrew.png'),
  applications: require('../../assets/images/applications.png'),
  noApplications: require('../../assets/images/no-applications.png'),
    reset: require('../../assets/images/reset.png'),
  gymIconThriveOne: require('../../assets/images/gym-icons-random/gym-icon-thrive-1.png'),
  gymIconEnergyOne: require('../../assets/images/gym-icons-random/gym-icon-energy-1.png'),
  gymIconBattleOne: require('../../assets/images/gym-icons-random/gym-icon-battle-1.png'),
  gymIconSpartaOne: require('../../assets/images/gym-icons-random/gym-icon-sparta-1.png'),
  gymIconUnderArmourOne: require('../../assets/images/gym-icons-random/gym-icon-under-armour-1.png'),
  gymIconAdidasOne: require('../../assets/images/gym-icons-random/gym-icon-adidas-1.png'),
  gymIconNikeOne: require('../../assets/images/gym-icons-random/gym-icon-nike-1.png'),
  gymIconBoxOne: require('../../assets/images/gym-icons-random/gym-icon-box-1.png'),
  gymIconSneakersOne: require('../../assets/images/gym-icons-random/gym-icon-sneakers-1.png'),
  gymIconSpearOne: require('../../assets/images/gym-icons-random/gym-icon-spear-1.png'),
  gymIconSparkOne: require('../../assets/images/gym-icons-random/gym-icon-spark-1.png'),
  gymIconSparkTwo: require('../../assets/images/gym-icons-random/gym-icon-spark-2.png'),
  gymIconLegsOne: require('../../assets/images/gym-icons-random/gym-icon-legs-1.png'),
  gymIconTorsoTwo: require('../../assets/images/gym-icons-random/gym-icon-torso-2.png'),
  gymIconRunningOne: require('../../assets/images/gym-icons-random/gym-icon-running-1.png'),
  gymIconTorsoOne: require('../../assets/images/gym-icons-random/gym-icon-torso-1.png'),
  gymIconDumbellOne: require('../../assets/images/gym-icons-random/gym-icon-dumbell-1.png'),
  gymIconDumbellTwo: require('../../assets/images/gym-icons-random/gym-icon-dumbell-2.png'),
  gymIconDumbellThree: require('../../assets/images/gym-icons-random/gym-icon-dumbell-3.png'),
  gymIconDumbellFour: require('../../assets/images/gym-icons-random/gym-icon-dumbell-4.png'),
  gymIconSmartWatchOne: require('../../assets/images/gym-icons-random/gym-icon-smart-watch-1.png'),
  gymIconMyFitnessPalOne: require('../../assets/images/gym-icons-random/gym-icon-myfitnesspal-1.png'),
  gymIconObeseOne: require('../../assets/images/gym-icons-random/gym-icon-obese-1.png'),
  gymIconNutritionOne: require('../../assets/images/gym-icons-random/gym-icon-nutrition-1.png'),
  gymIconNutritionTwo: require('../../assets/images/gym-icons-random/gym-icon-nutrition-2.png'),
  gymIconNutritionThree: require('../../assets/images/gym-icons-random/gym-icon-nutrition-3.png'),
  gymIconBicycleOne: require('../../assets/images/gym-icons-random/gym-icon-bicycle-1.png'),
  gymIconTimerOne: require('../../assets/images/gym-icons-random/gym-icon-timer-1.png'),
  gymIconHeartOne: require('../../assets/images/gym-icons-random/gym-icon-heart-1.png'),
  gymIconSkippingOne: require('../../assets/images/gym-icons-random/gym-icon-skipping-1.png'),
  gymIconWeightliftingOne: require('../../assets/images/gym-icons-random/gym-icon-weightlifting-1.png'),
  gymIconPullupsOne: require('../../assets/images/gym-icons-random/gym-icon-pullups-1.png'),
  gymIconBicepOne: require('../../assets/images/gym-icons-random/gym-icon-bicep-1.png'),
  gymIconSpartanWarriorOne: require('../../assets/images/gym-icons-random/gym-icon-spartan-warrior-1.png'),
  gymIconSpartanWarriorTwo: require('../../assets/images/gym-icons-random/gym-icon-spartan-warrior-2.png'),
  gymIconWarriorOne: require('../../assets/images/gym-icons-random/gym-icon-warrior-1.png'),
  gymIconFistOne: require('../../assets/images/gym-icons-random/gym-icon-fist-1.png'),
  gymIconHeartCheckOne: require('../../assets/images/gym-icons-random/gym-icon-heart-check-1.png'),
};

export const criticalAssets = [
  Images.home,
  Images.noHome,
  Images.browseCoaches,
  Images.noBrowseCoaches,
  Images.profile,
  Images.noProfile,
  Images.light,
  Images.dark,
  Images.settings,
  Images.profilePic,
  Images.noAffiliates,
  Images.notification,
  Images.noNotification,
  Images.applications,
  Images.noApplications,
  Images.gymIconThriveOne,
  Images.gymIconEnergyOne,
  Images.gymIconBattleOne,
  Images.gymIconSpartaOne,
  Images.gymIconUnderArmourOne,
  Images.gymIconAdidasOne,
  Images.gymIconNikeOne,
  Images.gymIconBoxOne,
  Images.gymIconSneakersOne,
  Images.gymIconSpearOne,
  Images.gymIconSparkOne,
  Images.gymIconLegsOne,
  Images.gymIconTorsoOne,
  Images.gymIconTorsoTwo,
  Images.gymIconRunningOne,
  Images.gymIconDumbellOne,
  Images.gymIconDumbellTwo,
  Images.gymIconDumbellThree,
  Images.gymIconDumbellFour,
  Images.gymIconSmartWatchOne,
  Images.gymIconMyFitnessPalOne,
  Images.gymIconObeseOne,
  Images.gymIconNutritionOne,
  Images.gymIconNutritionTwo,
  Images.gymIconNutritionThree,
  Images.gymIconBicycleOne,
  Images.gymIconTimerOne,
  Images.gymIconHeartOne,
  Images.gymIconSkippingOne,
  Images.gymIconWeightliftingOne,
  Images.gymIconPullupsOne,
  Images.gymIconBicepOne,
  Images.gymIconSpartanWarriorOne,
  Images.gymIconSpartanWarriorTwo,
  Images.gymIconWarriorOne,
  Images.gymIconFistOne,
  Images.gymIconHeartCheckOne,
];

export const nonCriticalAssets = [
    Images.logo,
  Images.rotate,
  Images.flashOn,
  Images.flashOff,
  Images.cameraSnap,
  Images.arrow,
  Images.darkProfileBackground,
  Images.lightProfileBackground,
  Images.personalDetails,
  Images.personalDetailsTwo,
  Images.settingsProfile,
  Images.settingsProfileTwo,
  Images.phone,
  Images.privacy,
  Images.logout,
  Images.instagram,
  Images.facebook,
  Images.linkedIn,
  Images.paperAirplane,
  Images.trash,
  Images.contact,
  Images.contactTwo,
  Images.xMark,
  Images.checkMark,
  Images.arrowDown,
  Images.save,
  Images.lock,
  Images.arabic,
  Images.hebrew,
  Images.english,
  Images.reset
];
